server {
    listen 8080;
    server_name localhost;

    # 1. 404 에러 방지 내비게이션 (React SPA 필수 설정)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 파일을 못 찾으면 무조건 index.html로 보내라!
        try_files $uri $uri/ /index.html;

        # 2. 깐깐한 보안 요원 무장 해제 (모든 통신과 인라인 코드 쿨하게 허용)
        add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob: wss: ws:;" always;
    }

    # 정적 자원(JS, CSS, 이미지) 경로 설정
    location ~* \.(?:css|js|jpg|svg|png|gif|ico|woff2?|eot|ttf|otf)$ {
        root /usr/share/nginx/html;
        add_header Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob: wss: ws:;" always;
    }
}
